### ISSUE TITLE
国内机器无法安装agent

### ISSUE THREAD

**Issue by NZESupB** [nezhahq/scripts#15]
gitee不存在latest标签，看v0的脚本是先获取的版本号再配置的链接

**Comment by Assen998** [comment]
配置终端代理就搞定了

**Comment by xuecanlong** [comment]
> 配置终端代理就搞定了

不是代理的问题  https://github.com/nezhahq/scripts/blob/main/agent/install.sh#L135 是没有latest这个release 应该要先获取version再下载

**Comment by uubulb** [comment]
。gitee太费了

**Comment by dyit-dalanmao** [comment]
V1 我安装了面板 怎么没有添加服务器的 地方   脚本也没有安装被控端的选项 这个 怎么办

**Comment by NZESupB** [comment]
> V1 我安装了面板 怎么没有添加服务器的 地方 脚本也没有安装被控端的选项 这个 怎么办

curl -L  https://raw.githubusercontent.com/nezhahq/scripts/main/agent/install.sh -o nezha.sh && chmod +x nezha.sh && env NZ_SERVER=ip:rpcport NZ_TLS=false NZ_CLIENT_SECRET=agentsecretkey ./nezha.sh
所有被控端都用这个指令就行，替换 ip:rpcport为 ip:8008 如果没改的话，或者rpc反代 agentsecretkey在config.yaml里面找

**Comment by NZESupB** [comment]
> 。gitee太费了

确实，临时配置代理安装上了。。

**Comment by dyit-dalanmao** [comment]
我不太明白的是  以前V0 上面有添加机器  然后 可以改名字啥的  这个目前我还没装上  目前点上面的linux 安装什么的 都是提示错误 让看日志什么的  这个 所有机器都运行一个命令 然后他发现以后再去改名？ NZ_CLIENT_SECRET=agentsecretkey       最后这个key要替换成 那串key吗
