### ISSUE TITLE
重复安装的问题

### ISSUE THREAD

**Issue by wanyunr** [nezhahq/scripts#18]
多次安装会产生多个配置文件，
希望**可以询问是覆盖**还是新增配置
![Clip_2024-11-30_21-42-16](https://github.com/user-attachments/assets/56e48a69-a208-4269-8bf7-c5db7a825084)

**Comment by uubulb** [comment]
目前 agent 脚本不打算加任何交互，
最多加一个卸载全部的 command

**Comment by wanyunr** [comment]
> 目前 agent 脚本不打算加任何交互， 最多加一个卸载全部的 command

不用交互也行吧，使用一个可选的参数选择覆盖安装或者重复安装，不然有时候很容易一台机器装了几个

**Comment by uubulb** [comment]
更好的办法是你自己了解脚本的行为，而不是什么功能都加，给你喂到嘴里

**Comment by wanyunr** [comment]
这只是一个建议
我是知道为什么会出现这种情况，不代表其他人会，我遇见很多人产生该问题，才来提issue的，并且我也自己提出了改进方法，不采纳就直接拒绝，而不是恶语相对

**Comment by uubulb** [comment]
文档之后会补卸载方法和agent支持多面板的特性
你代表那些人来发那你就要替他们接受后果，我只能说现在的小白被各种脚本惯的连服务器基本维护操作都不会
