### ISSUE TITLE
后台无法返回前端问题,未登录时无法查看服务页

### ISSUE THREAD

**Issue by Kook-9527** [nezhahq/scripts#25]
大佬你好,提两个优化小建议
1、现在进去后台管理貌似没有地方返回前端了,要去网址栏删掉后面的才能回到前端,有点不方便，能不能把后台左上角的“哪吒监控”logo点击的链接改为返回前端?
2、能不能在未登录时也能显示服务页的月度流量使用情况,还有就是ping值在没有勾选“服务中显示”的情况下也会在服务页显示,这是否也是一个bug?

**Comment by uubulb** [comment]
这个问题不应该在这里发
后台去 https://github.com/nezhahq/admin-frontend/issues
前台去 https://github.com/hamster1963/nezha-dash/issues

**Comment by Kook-9527** [comment]
> 这个问题不应该在这里发 后台去 https://github.com/nezhahq/admin-frontend/issues 前台去 https://github.com/hamster1963/nezha-dash/issues

好的谢谢
