### ISSUE TITLE
Docker报错

### ISSUE THREAD

**Issue by ovws** [nezhahq/scripts#3]
WARN[0000] /opt/nezha/dashboard/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
dashboard-1  | 2024/11/08 05:11:57 NEZHA>> Error parsing templates dashboard-custom: html/template: pattern matches no files: `resource/template/dashboard-custom/*.html`
dashboard-1  | 2024/11/08 05:11:57 NEZHA>> Error parsing templates theme-custom: html/template: pattern matches no files: `resource/template/theme-custom/*.html`

**Comment by uubulb** [comment]
默认自定义主题目录没有文件，所以导致报错没匹配到文件，不影响使用
