### ISSUE TITLE
standalone installation not implemented

### ISSUE THREAD

**Issue by TAXUEZJU** [nezhahq/scripts#4]
Notice the `install_dashboard_standalone` function actually installs nothing.

**Comment by uubulb** [comment]
It's mostly a naming issue, the original version of the script installs Docker in that step, but for standalone installation no additional runtime is required and it only created a folder. Maybe we'll change that later.

**Comment by TAXUEZJU** [comment]
Actually using the current script to install dashboard standalone will fail.

**Comment by uubulb** [comment]
This issue is closed and the topic has been resolved, so please open a new one instead.
