### ISSUE TITLE
Unable install dashboard in v0.20.13

### ISSUE THREAD

**Issue by emoless789** [nezhahq/scripts#5]
use one tap install but not success
---------log---------
root@iZuf6elnh24amumv43l68yZ:~# ./nezha.sh -x
根据geoip api提供的信息，当前IP可能在中国
是否选用中国镜像完成安装? [Y/n] (自定义镜像输入 3)：y
使用中国镜像
哪吒监控 管理脚本使用方法: 
--------------------------------------------------------
./nezha.sh                            - 显示管理菜单
./nezha.sh install_dashboard          - 安装面板端
./nezha.sh modify_dashboard_config    - 修改面板配置
./nezha.sh start_dashboard            - 启动面板
./nezha.sh stop_dashboard             - 停止面板
./nezha.sh restart_and_update         - 重启并更新面板
./nezha.sh show_dashboard_log         - 查看面板日志
./nezha.sh uninstall_dashboard        - 卸载管理面板
--------------------------------------------------------
./nezha.sh install_agent              - 安装监控Agent
./nezha.sh modify_agent_config        - 修改Agent配置
./nezha.sh show_agent_log             - 查看Agent日志
./nezha.sh uninstall_agent            - 卸载Agent
./nezha.sh restart_agent              - 重启Agent
./nezha.sh update_script              - 更新脚本
--------------------------------------------------------
root@iZuf6elnh24amumv43l68yZ:~# ./nezha.sh install_dashboard -x
根据geoip api提供的信息，当前IP可能在中国
是否选用中国镜像完成安装? [Y/n] (自定义镜像输入 3)：y
使用中国镜像
> 安装面板
您可能已经安装过面板端，重复安装会覆盖数据，请注意备份。
是否退出安装? [Y/n] n
继续安装
> 修改 Dashboard 配置
关于 GitHub Oauth2 应用：在 https://github.com/settings/developers 创建，无需审核，Callback 填 http(s)://域名或IP/oauth2/callback
关于 Gitee Oauth2 应用：在 https://gitee.com/oauth/applications 创建，无需审核，Callback 填 http(s)://域名或IP/oauth2/callback
请输入 OAuth2 提供商(github/gitlab/jihulab/gitee，默认 github): 
请输入 Oauth2 应用的 Client ID: 
请输入 Oauth2 应用的 Client Secret: 
请输入 GitHub/Gitee 登录名作为管理员，多个以逗号隔开: emoless789
请输入站点标题: monitor
请输入站点访问端口: (默认 8008)8008
请输入用于 Agent 接入的 RPC 端口: (默认 5555)5555
正在下载服务文件
Dashboard 配置 修改成功，请稍等 Dashboard 重启生效
> 重启并更新面板
当前最新版本为： v0.20.13
Failed to stop nezha-dashboard.service: Unit nezha-dashboard.service not loaded.
Failed to enable unit: Unit file nezha-dashboard.service does not exist.
Failed to restart nezha-dashboard.service: Unit nezha-dashboard.service not found.
重启失败，可能是因为启动时间超过了两秒，请稍后查看日志信息

* 按回车返回主菜单 *

OS: Debian GNU/Linux 12 (bookworm) x86_64
Host: Alibaba Cloud ECS pc-i440fx-2.1
Kernel: 6.1.0-26-amd64

**Comment by uubulb** [comment]
`bash -x ./nezha.sh`
把日志放代码块里

**Comment by uubulb** [comment]
已修复
